import re
import os
import sys
import time
import shutil
from bs4 import BeautifulSoup
from deep_translator import GoogleTranslator
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

# Fix Windows console encoding for Emojis
if sys.platform.startswith('win'):
    sys.stdout.reconfigure(encoding='utf-8')
    sys.stderr.reconfigure(encoding='utf-8')

HTML_SOURCE = r"g:\My Drive\Dev\Einstein\index.html"
HTML_DEST = r"g:\My Drive\Arx Capital\web\arxWeb\nice.html"
HTML_DEST_SUB = r"g:\My Drive\Arx Capital\web\arxWeb\Nice\index.html"
NOTE_SOURCE = r"g:\My Drive\Dev\Einstein\Note_de_Position_Nice_IA_Ciotti.md"
NOTE_DEST = r"g:\My Drive\Arx Capital\web\arxWeb\Note_de_Position_Nice_IA_Ciotti.md"
NOTE_DEST_SUB = r"g:\My Drive\Arx Capital\web\arxWeb\Nice\Note_de_Position_Nice_IA_Ciotti.md"

# Translators and mapping cache
translator = GoogleTranslator(source='fr', target='en')
translation_cache = {}

def html_id_to_js_key(html_id):
    mapping = {
        "roi-lbl-gross": "roiGross",
        "roi-lbl-cost": "roiCost",
        "roi-lbl-net": "roiNet",
        "roi-cost-val": "roiCostVal"
    }
    if html_id in mapping:
        return mapping[html_id]
    
    m = re.match(r"tab(\d+)-card(\d+)-(\w+)", html_id)
    if m:
        return f"tab{m.group(1)}card{m.group(2)}{m.group(3)}"
        
    m_bm = re.match(r"bm-(\d+)-(\w+)", html_id)
    if m_bm:
        return f"bm{m_bm.group(1)}{m_bm.group(2)}"
        
    m_m = re.match(r"m(\d+)-b(\d+)-(\w+)", html_id)
    if m_m:
        return f"m{m_m.group(1)}b{m_m.group(2)}{m_m.group(3)}"
        
    parts = html_id.split('-')
    if len(parts) > 1:
        return parts[0] + ''.join(x.title() for x in parts[1:])
    return html_id

def clean_inner_html(html_str):
    # Normalize spaces and newlines
    html_str = html_str.strip()
    html_str = re.sub(r'\s+', ' ', html_str)
    return html_str

def parse_pairs(block_text):
    pairs = {}
    # Matches key: "value" (supports escaped quotes)
    matches = re.findall(r'(\w+):\s*"([^"\\]*(?:\\.[^"\\]*)*)"', block_text)
    for k, v in matches:
        # Unescape quotes
        v_unescaped = v.replace('\\"', '"').replace('\\n', '\n')
        pairs[k] = v_unescaped
    return pairs

def translate_text(text):
    if not text or text.strip() == "" or text.isdigit():
        return text
    try:
        # Keep basic HTML tags intact if possible
        translated = translator.translate(text)
        if translated is not None:
            return translated
    except Exception as e:
        print(f"Translation error: {e}")
    return text

def process_file():
    print(f"[{time.strftime('%H:%M:%S')}] Processing changes in {HTML_SOURCE}...")
    
    try:
        with open(HTML_SOURCE, "r", encoding="utf-8") as f:
            content = f.read()
            
        soup = BeautifulSoup(content, "html.parser")
        
        # 1. Extract current FR and EN i18n blocks
        fr_match = re.search(r"FR:\s*\{(.*?)\},\s*EN:", content, re.DOTALL)
        en_match = re.search(r"EN:\s*\{(.*?)\}\s*\n\s*\};", content, re.DOTALL)
        
        if not fr_match or not en_match:
            print("Could not locate FR or EN i18n block in script.")
            return False
            
        fr_pairs = parse_pairs(fr_match.group(1))
        en_pairs = parse_pairs(en_match.group(1))
        
        # 2. Extract texts from HTML body using IDs to sync back to FR dictionary
        # This allows the user to edit either the HTML elements directly or the FR dictionary.
        html_changes = 0
        for el in soup.find_all(id=True):
            el_id = el["id"]
            js_key = html_id_to_js_key(el_id)
            if js_key in fr_pairs:
                # Get the inner HTML content of the element in the actual HTML source
                # (Note: we get the raw content to preserve inner HTML formatting like strong/em/br)
                # We use string representation of children to get inner HTML
                inner_html = "".join([str(c) for c in el.contents])
                inner_html = clean_inner_html(inner_html)
                
                # Check if it differs from current FR dict
                current_fr_val = clean_inner_html(fr_pairs[js_key])
                if inner_html and inner_html != current_fr_val:
                    # Exclude placeholders or active values generated by JS (like counter digits)
                    if "flip-counter" in inner_html or "flip-digit" in inner_html:
                        continue
                    print(f"  [HTML -> FR] Detected change in element #{el_id}: '{current_fr_val[:30]}' -> '{inner_html[:30]}'")
                    fr_pairs[js_key] = inner_html
                    html_changes += 1
                    
        # 3. Check for any changed/new keys in FR and translate them to EN (GB)
        translations_count = 0
        for key in list(fr_pairs.keys()):
            fr_val = fr_pairs[key]
            # If key is missing from EN, or if FR value has changed relative to what was translated
            if key not in en_pairs or fr_val != translation_cache.get(key, None):
                # Save to cache
                translation_cache[key] = fr_val
                
                # Perform translation
                print(f"  [Translating] '{key}': '{fr_val[:40]}...'")
                en_val = translate_text(fr_val)
                en_pairs[key] = en_val
                translations_count += 1
            else:
                # Keep cache in sync for existing entries
                translation_cache[key] = fr_val

        out_fr_pairs = fr_pairs
        out_en_pairs = en_pairs

        # 4. Reconstruct FR and EN blocks in JS
        fr_lines = []
        for k in sorted(out_fr_pairs.keys()):
            val = out_fr_pairs.get(k) or ""
            val_escaped = str(val).replace('"', '\\"').replace('\n', '\\n')
            fr_lines.append(f'                {k}: "{val_escaped}",')
        fr_block_new = "\n" + "\n".join(fr_lines) + "\n            "
        
        en_lines = []
        for k in sorted(out_en_pairs.keys()):
            val = out_en_pairs.get(k) or ""
            val_escaped = str(val).replace('"', '\\"').replace('\n', '\\n')
            en_lines.append(f'                {k}: "{val_escaped}",')
        en_block_new = "\n" + "\n".join(en_lines) + "\n            "
        
        # Replace in original file content
        new_content = content
        new_content = re.sub(r"(FR:\s*\{)(.*?)(Simple replacement target blocker to avoid bad regex matches|P\d+)?(\},\s*EN:)", 
                             lambda m: f"{m.group(1)}{fr_block_new}{m.group(4)}", new_content, flags=re.DOTALL)
        
        # Now replace EN
        # For EN, target: EN: { ... } };
        new_content = re.sub(r"(EN:\s*\{)(.*?)(Simple replacement target blocker to avoid bad regex matches|P\d+)?(\}\s*\n\s*\};)", 
                             lambda m: f"{m.group(1)}{en_block_new}{m.group(4)}", new_content, flags=re.DOTALL)
                             
        # Save to index.html if changed
        if new_content != content:
            with open(HTML_SOURCE, "w", encoding="utf-8") as f:
                f.write(new_content)
            print(f"  [Saved] Updated {HTML_SOURCE} with {translations_count} translations.")
        else:
            print("  [No-op] Translation dictionaries are up to date.")
            
        # 5. Sync files to arxWeb production (OCI)
        print(f"  [Syncing] Copying updated files to arxWeb production...")
        shutil.copy2(HTML_SOURCE, HTML_DEST)
        shutil.copy2(HTML_SOURCE, HTML_DEST_SUB)
        shutil.copy2(NOTE_SOURCE, NOTE_DEST)
        shutil.copy2(NOTE_SOURCE, NOTE_DEST_SUB)
        print("  [Sync OK] Files successfully copied to OCI.")
        return True
        
    except Exception as e:
        print(f"Error during processing: {e}")
        import traceback
        traceback.print_exc()
        return False

class FileChangeHandler(FileSystemEventHandler):
    def __init__(self):
        self.last_run = 0
        
    def on_modified(self, event):
        # Prevent double triggers (debounce)
        if event.src_path == HTML_SOURCE or event.src_path == NOTE_SOURCE:
            now = time.time()
            if now - self.last_run > 2:
                self.last_run = now
                # Delay slightly to ensure write finishes
                time.sleep(0.5)
                process_file()

if __name__ == "__main__":
    print("==================================================")
    print(" Nice IA 2026 — Automated Translation & Sync")
    print("==================================================")
    
    # Run once
    process_file()
    
    # Start watching only if --watch argument is provided
    if len(sys.argv) > 1 and sys.argv[1] == "--watch":
        print("\n[Mode Watch] Watching for changes in index.html & Note_de_Position...")
        path_to_watch = os.path.dirname(HTML_SOURCE)
        event_handler = FileChangeHandler()
        observer = Observer()
        observer.schedule(event_handler, path=path_to_watch, recursive=False)
        observer.start()
        
        try:
            while True:
                time.sleep(1)
        except KeyboardInterrupt:
            observer.stop()
        observer.join()
    else:
        print("\n[Done] One-shot translation and sync completed successfully. Exiting.")
